apiVersion: v1
kind: Service
metadata:
  name: capper-peers
spec:
  selector:
    app: capper
    component: server
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: serf
    protocol: TCP
    port: 7946
    targetPort: 7946
