apiVersion: v1
kind: Service
metadata:
  name: capper-gateway
spec:
  selector:
    app: capper
    component: gateway
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 48999
    targetPort: 48999
