apiVersion: v1
kind: Service
metadata:
  name: capper-server
spec:
  selector:
    app: capper
    component: server
  type: ClusterIP
  clusterIP: None
  ports:
  - name: grpc
    protocol: TCP
    port: 48999
    targetPort: 48999
