// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: proto/capper/querier.proto

package capper

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CaptureQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Targets        []*CaptureQueryTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	CaptureRequest *CaptureRequest       `protobuf:"bytes,2,opt,name=capture_request,json=captureRequest,proto3" json:"capture_request,omitempty"`
}

func (x *CaptureQueryRequest) Reset() {
	*x = CaptureQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_capper_querier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureQueryRequest) ProtoMessage() {}

func (x *CaptureQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capper_querier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureQueryRequest.ProtoReflect.Descriptor instead.
func (*CaptureQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_capper_querier_proto_rawDescGZIP(), []int{0}
}

func (x *CaptureQueryRequest) GetTargets() []*CaptureQueryTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *CaptureQueryRequest) GetCaptureRequest() *CaptureRequest {
	if x != nil {
		return x.CaptureRequest
	}
	return nil
}

type CaptureQueryTarget struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Target:
	//
	//	*CaptureQueryTarget_Node
	//	*CaptureQueryTarget_Pod
	Target isCaptureQueryTarget_Target `protobuf_oneof:"target"`
}

func (x *CaptureQueryTarget) Reset() {
	*x = CaptureQueryTarget{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_capper_querier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureQueryTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureQueryTarget) ProtoMessage() {}

func (x *CaptureQueryTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capper_querier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureQueryTarget.ProtoReflect.Descriptor instead.
func (*CaptureQueryTarget) Descriptor() ([]byte, []int) {
	return file_proto_capper_querier_proto_rawDescGZIP(), []int{1}
}

func (m *CaptureQueryTarget) GetTarget() isCaptureQueryTarget_Target {
	if m != nil {
		return m.Target
	}
	return nil
}

func (x *CaptureQueryTarget) GetNode() string {
	if x, ok := x.GetTarget().(*CaptureQueryTarget_Node); ok {
		return x.Node
	}
	return ""
}

func (x *CaptureQueryTarget) GetPod() *K8SPodFilter {
	if x, ok := x.GetTarget().(*CaptureQueryTarget_Pod); ok {
		return x.Pod
	}
	return nil
}

type isCaptureQueryTarget_Target interface {
	isCaptureQueryTarget_Target()
}

type CaptureQueryTarget_Node struct {
	Node string `protobuf:"bytes,1,opt,name=node,proto3,oneof"`
}

type CaptureQueryTarget_Pod struct {
	Pod *K8SPodFilter `protobuf:"bytes,2,opt,name=pod,proto3,oneof"`
}

func (*CaptureQueryTarget_Node) isCaptureQueryTarget_Target() {}

func (*CaptureQueryTarget_Pod) isCaptureQueryTarget_Target() {}

type CaptureQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
	LinkType   int64  `protobuf:"varint,3,opt,name=link_type,json=linkType,proto3" json:"link_type,omitempty"`
	NodeName   string `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
}

func (x *CaptureQueryResponse) Reset() {
	*x = CaptureQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_capper_querier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CaptureQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureQueryResponse) ProtoMessage() {}

func (x *CaptureQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_capper_querier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureQueryResponse.ProtoReflect.Descriptor instead.
func (*CaptureQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_capper_querier_proto_rawDescGZIP(), []int{2}
}

func (x *CaptureQueryResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CaptureQueryResponse) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *CaptureQueryResponse) GetLinkType() int64 {
	if x != nil {
		return x.LinkType
	}
	return 0
}

func (x *CaptureQueryResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

var File_proto_capper_querier_proto protoreflect.FileDescriptor

var file_proto_capper_querier_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x71,
	0x75, 0x65, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x61,
	0x70, 0x70, 0x65, 0x72, 0x1a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x70, 0x70,
	0x65, 0x72, 0x2f, 0x63, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x8c, 0x01, 0x0a, 0x13, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x61, 0x70, 0x70, 0x65,
	0x72, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x52, 0x07, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x73, 0x12, 0x3f, 0x0a,
	0x0f, 0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e,
	0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0e,
	0x63, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5e,
	0x0a, 0x12, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x54, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x28, 0x0a, 0x03, 0x70, 0x6f,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x61, 0x70, 0x70, 0x65, 0x72,
	0x2e, 0x4b, 0x38, 0x73, 0x50, 0x6f, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x03, 0x70, 0x6f, 0x64, 0x42, 0x08, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x84,
	0x01, 0x0a, 0x14, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6c,
	0x69, 0x6e, 0x6b, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x58, 0x0a, 0x07, 0x51, 0x75, 0x65, 0x72, 0x69, 0x65, 0x72,
	0x12, 0x4d, 0x0a, 0x0c, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x12, 0x1b, 0x2e, 0x63, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72,
	0x65, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x63, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2e, 0x43, 0x61, 0x70, 0x74, 0x75, 0x72, 0x65, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42,
	0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68,
	0x61, 0x6e, 0x63, 0x65, 0x7a, 0x2f, 0x63, 0x61, 0x70, 0x70, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x63, 0x61, 0x70, 0x70, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_capper_querier_proto_rawDescOnce sync.Once
	file_proto_capper_querier_proto_rawDescData = file_proto_capper_querier_proto_rawDesc
)

func file_proto_capper_querier_proto_rawDescGZIP() []byte {
	file_proto_capper_querier_proto_rawDescOnce.Do(func() {
		file_proto_capper_querier_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_capper_querier_proto_rawDescData)
	})
	return file_proto_capper_querier_proto_rawDescData
}

var file_proto_capper_querier_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_capper_querier_proto_goTypes = []interface{}{
	(*CaptureQueryRequest)(nil),  // 0: capper.CaptureQueryRequest
	(*CaptureQueryTarget)(nil),   // 1: capper.CaptureQueryTarget
	(*CaptureQueryResponse)(nil), // 2: capper.CaptureQueryResponse
	(*CaptureRequest)(nil),       // 3: capper.CaptureRequest
	(*K8SPodFilter)(nil),         // 4: capper.K8sPodFilter
}
var file_proto_capper_querier_proto_depIdxs = []int32{
	1, // 0: capper.CaptureQueryRequest.targets:type_name -> capper.CaptureQueryTarget
	3, // 1: capper.CaptureQueryRequest.capture_request:type_name -> capper.CaptureRequest
	4, // 2: capper.CaptureQueryTarget.pod:type_name -> capper.K8sPodFilter
	0, // 3: capper.Querier.CaptureQuery:input_type -> capper.CaptureQueryRequest
	2, // 4: capper.Querier.CaptureQuery:output_type -> capper.CaptureQueryResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_capper_querier_proto_init() }
func file_proto_capper_querier_proto_init() {
	if File_proto_capper_querier_proto != nil {
		return
	}
	file_proto_capper_capper_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_capper_querier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_capper_querier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureQueryTarget); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_capper_querier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CaptureQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_capper_querier_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CaptureQueryTarget_Node)(nil),
		(*CaptureQueryTarget_Pod)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_capper_querier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_capper_querier_proto_goTypes,
		DependencyIndexes: file_proto_capper_querier_proto_depIdxs,
		MessageInfos:      file_proto_capper_querier_proto_msgTypes,
	}.Build()
	File_proto_capper_querier_proto = out.File
	file_proto_capper_querier_proto_rawDesc = nil
	file_proto_capper_querier_proto_goTypes = nil
	file_proto_capper_querier_proto_depIdxs = nil
}
